//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnchoredinHim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public string ArchivesID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual DailyDevotional DailyDevotional { get; set; }
        public virtual Event Event { get; set; }
    }
}
