//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnchoredinHim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public string BlogID { get; set; }
        public string Post { get; set; }
    
        public virtual Archive Archive { get; set; }
    }
}
