//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnchoredinHim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnchoredinHimEntities1 : DbContext
    {
        public AnchoredinHimEntities1()
            : base("name=AnchoredinHimEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archive> Archives { get; set; }
        public virtual DbSet<ATeamBmore> ATeamBmores { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<DailyDevotional> DailyDevotionals { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Volunteer> Volunteers { get; set; }
    }
}
